### ISSUE TITLE
Not loading in latest HA

### ISSUE THREAD

**Issue by nickidw** [tinuva/ha-coct-loadshedding#7]
## Version of the custom_component

1.0.8
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
Not loading after upgrade to HA 2025.6.1. Worked in 2025.5 releases.

## Debug log

```text

Log details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 13:43:28 (3 occurrences)
Last logged: 14:42:08

Error setting up entry Home for coct_loadshedding
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/coct_loadshedding/__init__.py", line 60, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?


```

**Comment by bass225** [comment]
@nickidw same here

**Comment by tinuva** [comment]
I've pushed a new release that "might" fix the issue. 

Try version 1.0.9

Just a heads up, I am not really maintaining this addon anymore, with [load_shedding](https://github.com/wernerhp/ha.integration.load_shedding) being far superior than this one.

**Comment by nickidw** [comment]
> I've pushed a new release that "might" fix the issue.
> 
> Try version 1.0.9
> 
> Just a heads up, I am not really maintaining this addon anymore, with [load_shedding](https://github.com/wernerhp/ha.integration.load_shedding) being far superior than this one.

Thank you, it appears to have solved the issue, much appreciated!
